Task9
ithillel-php-basic/php-basic-2-63e5048c1c12e7422818a949 pull request #8
Opened 2023-06-02 10:54 UTC by volodkaly

task 9 attempt #1
db_connect.php added
seems to be working
no sql injection protection yet

2023-06-02 19:27 UTC, alexpalyan requested changes

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +$userProjectsQuery = "SELECT * FROM categories WHERE author_id = 1";
autor_id передається аргументом ) Як варіант, можна використовувати його )

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +$userTasksQuery = "SELECT * FROM tasks WHERE author_id = 1";
autor_id передається аргументом ) Як варіант, можна використовувати його )

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +        echo "Назва проєкту: " . $row["name"] . "<br>";
Функція не повинна нічого виводити ) Тільки формувати відповідь і віддавати її в результаті )

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +    echo "Немає проєктів для поточного користувача";
Функція не повинна нічого виводити ) Тільки формувати відповідь і віддавати її в результаті )

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +        echo "Назва завдання: " . $row["title"] . "<br>";
Функція не повинна нічого виводити ) Тільки формувати відповідь і віддавати її в результаті )

2023-06-02 19:27 UTC, alexpalyan commented on db_connect.php
> +    echo "Немає завдань для поточного користувача";
Функція не повинна нічого виводити ) Тільки формувати відповідь і віддавати її в результаті )

Формування виводу в нас тільки через шаблони

2023-06-11 11:38 UTC, volodkaly commented
closed

2023-06-11 11:38 UTC, closed without merging