Task12
ithillel-php-basic/php-basic-2-63e5048c1c12e7422818a949 pull request #9
Opened 2023-06-08 10:57 UTC by volodkaly

ще я так розумію не до кінця готова безпека скл запитів і взагалі звичайно як завжди все треба буде переробити, 
але прошу принаймні частину балів, бо якось щось все є таки працює і довго над цим працював)

2023-06-10 18:57 UTC, alexpalyan requested changes

2023-06-10 18:57 UTC, alexpalyan commented on  queries.sql
> + VALUES (1,'2023-05-23', 'user5@example.com', 'Користувач 1', 'password1'),
Тут тепер помилка у запиті. Це дуже важливо не редагувати файли які не відносяться до задачі якщо немає дуже поважних причин для цього (наприклад, виправлення критичної помилки)

2023-06-10 18:57 UTC, alexpalyan commented on register.php
> +$content = @renderTemplate('register.php', [
Подавлення помилок не допускається

2023-06-10 18:57 UTC, alexpalyan commented on register.php
> +        'email' => $email,
Warning: Undefined variable $email in /var/www/public/register.php on line 62

2023-06-10 18:57 UTC, alexpalyan commented on register.php
> +        unset($password);
Для чого відбувається видалення змінних?

2023-06-10 18:57 UTC, alexpalyan commented on register.php
> +        unset($email);
Це видалення викликає помилку потім

2023-06-10 18:57 UTC, alexpalyan commented on register2.html
> +<!DOCTYPE html>
Цього файлу не повинно бути по завданню )

2023-06-10 18:57 UTC, alexpalyan commented on templates/kanban.php
> +           <a href="register.php" style="font-size: 20px;" style="background-color: yellow; color: red;">Реєстрація</a>
Цих рядків не повинно бути, бо неавторизований користувач не зможе бачити цю сторінку по ТЗ )

2023-06-11 11:36 UTC, volodkaly commented
partly solved

2023-06-11 11:36 UTC, closed without merging